spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver    # 驱动
        url: "jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT"    # 数据库url
        username: "root"    # 用户名
        password: "12345678"    # 密码
    jpa:
        hibernate:
            ddl-auto: update    # 实体类与表结构不一样时执行的操作
            dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true    # 控制台输出SQL语句
logging:
    level:
        root: info    # root日志级别
        com.daozhi: debug    # 包日志级别
    file:
        name: log/blog-dev.log    # 日志文件位置，默认10M切分
server:
    port: 80    # 生产环境端口
